apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-workflow
rules:
- apiGroups: [argoproj.io]
  resources: [workflowtaskresults]
  verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-workflow
subjects:
- kind: ServiceAccount
  name: platform-workflow
  namespace: platform-apps
