---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: anthonycorletti/krm-examples-rails-postgres:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: "production"
            - name: DATABASE_WRITER_URL
              valueFrom:
                secretKeyRef:
                  name: rails-app-secrets
                  key: database_writer_url
            - name: DATABASE_READER_URL
              valueFrom:
                secretKeyRef:
                  name: rails-app-secrets
                  key: database_reader_url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-app-secrets
                  key: secret_key_base
          readinessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /up
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
