"""Add experimentation metadata and record lifecycle fields.

Conversation bodies and artifacts belong in object storage, referenced by key.
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column("verification", "id", type_=sa.String(), postgresql_using="id::text")
    op.add_column(
        "verification",
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.alter_column("verification", "updated_at", server_default=None)
    op.add_column(
        "verification", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index("ix_verification_deleted_at", "verification", ["deleted_at"])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("environment", sa.String(), nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_deleted_at"), "project", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_project_environment"), "project", ["environment"], unique=False)
    op.create_index(op.f("ix_project_owner"), "project", ["owner"], unique=False)
    op.create_table(
        "task",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("agent", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("history_key", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_deleted_at"), "task", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_task_project_id"), "task", ["project_id"], unique=False)
    op.create_table(
        "run",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("prompt_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("workflow_name", sa.String(), nullable=True),
        sa.Column("trace_id", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_deleted_at"), "run", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_run_status"), "run", ["status"], unique=False)
    op.create_index(op.f("ix_run_task_id"), "run", ["task_id"], unique=False)
    op.create_table(
        "artifact",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artifact_deleted_at"), "artifact", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_artifact_run_id"), "artifact", ["run_id"], unique=False)
    op.create_index(op.f("ix_artifact_task_id"), "artifact", ["task_id"], unique=False)
    op.create_table(
        "event",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_deleted_at"), "event", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_event_run_id"), "event", ["run_id"], unique=False)
    op.create_index(op.f("ix_event_task_id"), "event", ["task_id"], unique=False)
    op.create_table(
        "message",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_deleted_at"), "message", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_message_run_id"), "message", ["run_id"], unique=False)
    op.create_index(op.f("ix_message_task_id"), "message", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("message")
    op.drop_table("event")
    op.drop_table("artifact")
    op.drop_table("run")
    op.drop_table("task")
    op.drop_table("project")
    op.drop_index("ix_verification_deleted_at", table_name="verification")
    op.drop_column("verification", "deleted_at")
    op.drop_column("verification", "updated_at")
    # Legacy UUIDs retain their value; new ULIDs receive deterministic UUIDs on rollback.
    op.alter_column(
        "verification",
        "id",
        type_=sa.Uuid(),
        postgresql_using="CASE WHEN length(id) = 36 THEN id::uuid ELSE md5(id)::uuid END",
    )
