apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: platform-postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.9-system-trixie@sha256:8fd8db26090e602458269741849e5c9cd7aff577a22af53c8a402c580fd1e729
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: platform
      owner: platform
  storage:
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
