// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelTaskData, CancelTaskErrors, CancelTaskResponses, CreateProjectData, CreateProjectErrors, CreateProjectResponses, CreateTaskData, CreateTaskErrors, CreateTaskResponses, DeleteProjectData, DeleteProjectErrors, DeleteProjectResponses, DeleteTaskData, DeleteTaskErrors, DeleteTaskResponses, ListAgentsData, ListAgentsResponses, ListComponentsData, ListComponentsErrors, ListComponentsResponses, ListProjectsData, ListProjectsResponses, ListTasksData, ListTasksErrors, ListTasksResponses, ListVerificationsData, ListVerificationsErrors, ListVerificationsResponses, ReadArtifactData, ReadArtifactErrors, ReadArtifactResponses, ReadAuthConfigData, ReadAuthConfigResponses, ReadIdentityData, ReadIdentityResponses, ReadLivenessData, ReadLivenessResponses, ReadMigrationsData, ReadMigrationsErrors, ReadMigrationsResponses, ReadReadinessData, ReadReadinessResponses, ReadTaskData, ReadTaskErrors, ReadTaskResponses, RunVerificationData, RunVerificationErrors, RunVerificationResponses, SendMessageData, SendMessageErrors, SendMessageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Agents
 */
export const listAgents = <ThrowOnError extends boolean = false>(options?: Options<ListAgentsData, ThrowOnError>) => (options?.client ?? client).get<ListAgentsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/agents',
    ...options
});

/**
 * Config
 */
export const readAuthConfig = <ThrowOnError extends boolean = false>(options?: Options<ReadAuthConfigData, ThrowOnError>) => (options?.client ?? client).get<ReadAuthConfigResponses, unknown, ThrowOnError>({ url: '/api/auth/config', ...options });

/**
 * Me
 */
export const readIdentity = <ThrowOnError extends boolean = false>(options?: Options<ReadIdentityData, ThrowOnError>) => (options?.client ?? client).get<ReadIdentityResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/auth/me',
    ...options
});

/**
 * List Components
 */
export const listComponents = <ThrowOnError extends boolean = false>(options?: Options<ListComponentsData, ThrowOnError>) => (options?.client ?? client).get<ListComponentsResponses, ListComponentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/components',
    ...options
});

/**
 * Read Migrations
 */
export const readMigrations = <ThrowOnError extends boolean = false>(options?: Options<ReadMigrationsData, ThrowOnError>) => (options?.client ?? client).get<ReadMigrationsResponses, ReadMigrationsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/migrations',
    ...options
});

/**
 * List Projects
 */
export const listProjects = <ThrowOnError extends boolean = false>(options?: Options<ListProjectsData, ThrowOnError>) => (options?.client ?? client).get<ListProjectsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects',
    ...options
});

/**
 * Create Project
 */
export const createProject = <ThrowOnError extends boolean = false>(options: Options<CreateProjectData, ThrowOnError>) => (options.client ?? client).post<CreateProjectResponses, CreateProjectErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Project
 */
export const deleteProject = <ThrowOnError extends boolean = false>(options: Options<DeleteProjectData, ThrowOnError>) => (options.client ?? client).delete<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}',
    ...options
});

/**
 * Tasks
 */
export const listTasks = <ThrowOnError extends boolean = false>(options: Options<ListTasksData, ThrowOnError>) => (options.client ?? client).get<ListTasksResponses, ListTasksErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/tasks',
    ...options
});

/**
 * Create
 */
export const createTask = <ThrowOnError extends boolean = false>(options: Options<CreateTaskData, ThrowOnError>) => (options.client ?? client).post<CreateTaskResponses, CreateTaskErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/projects/{project_id}/tasks',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete
 */
export const deleteTask = <ThrowOnError extends boolean = false>(options: Options<DeleteTaskData, ThrowOnError>) => (options.client ?? client).delete<DeleteTaskResponses, DeleteTaskErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tasks/{task_id}',
    ...options
});

/**
 * Read
 */
export const readTask = <ThrowOnError extends boolean = false>(options: Options<ReadTaskData, ThrowOnError>) => (options.client ?? client).get<ReadTaskResponses, ReadTaskErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tasks/{task_id}',
    ...options
});

/**
 * Artifact
 */
export const readArtifact = <ThrowOnError extends boolean = false>(options: Options<ReadArtifactData, ThrowOnError>) => (options.client ?? client).get<ReadArtifactResponses, ReadArtifactErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tasks/{task_id}/artifacts/{artifact_id}',
    ...options
});

/**
 * Cancel
 */
export const cancelTask = <ThrowOnError extends boolean = false>(options: Options<CancelTaskData, ThrowOnError>) => (options.client ?? client).post<CancelTaskResponses, CancelTaskErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tasks/{task_id}/cancel',
    ...options
});

/**
 * Send
 */
export const sendMessage = <ThrowOnError extends boolean = false>(options: Options<SendMessageData, ThrowOnError>) => (options.client ?? client).post<SendMessageResponses, SendMessageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/tasks/{task_id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Verifications
 */
export const listVerifications = <ThrowOnError extends boolean = false>(options?: Options<ListVerificationsData, ThrowOnError>) => (options?.client ?? client).get<ListVerificationsResponses, ListVerificationsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/verifications',
    ...options
});

/**
 * Run Verification
 */
export const runVerification = <ThrowOnError extends boolean = false>(options: Options<RunVerificationData, ThrowOnError>) => (options.client ?? client).post<RunVerificationResponses, RunVerificationErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/verifications',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Livez
 */
export const readLiveness = <ThrowOnError extends boolean = false>(options?: Options<ReadLivenessData, ThrowOnError>) => (options?.client ?? client).get<ReadLivenessResponses, unknown, ThrowOnError>({ url: '/livez', ...options });

/**
 * Readyz
 */
export const readReadiness = <ThrowOnError extends boolean = false>(options?: Options<ReadReadinessData, ThrowOnError>) => (options?.client ?? client).get<ReadReadinessResponses, unknown, ThrowOnError>({ url: '/readyz', ...options });
