// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * AgentRead
 */
export type AgentRead = {
    /**
     * Available
     */
    available: boolean;
    /**
     * Description
     */
    description: string;
    /**
     * Id
     */
    id: string;
    /**
     * Model
     */
    model: string;
    /**
     * Name
     */
    name: string;
};

/**
 * Artifact
 */
export type Artifact = {
    /**
     * Content Type
     */
    content_type?: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Object Key
     */
    object_key: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Sha256
     */
    sha256: string;
    /**
     * Size
     */
    size: number;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * AuthConfig
 */
export type AuthConfig = {
    /**
     * Client Id
     */
    client_id: string | null;
    /**
     * Environment
     */
    environment: string;
    /**
     * Issuer
     */
    issuer: string | null;
};

/**
 * ComponentRead
 */
export type ComponentRead = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'ready' | 'unavailable' | 'unverified' | 'not_configured' | 'not_implemented';
};

/**
 * Event
 */
export type Event = {
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Object Key
     */
    object_key?: string | null;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MessageCreate
 */
export type MessageCreate = {
    /**
     * Content
     */
    content: string;
};

/**
 * MessageRead
 */
export type MessageRead = {
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * MigrationRead
 */
export type MigrationRead = {
    /**
     * Applied
     */
    applied: string | null;
    /**
     * Current
     */
    current: boolean;
    /**
     * Expected
     */
    expected: string;
};

/**
 * Principal
 */
export type Principal = {
    /**
     * Environment
     */
    environment: string;
    /**
     * Scopes
     */
    scopes: Array<string>;
    /**
     * Subject
     */
    subject: string;
};

/**
 * Project
 */
export type Project = {
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Description
     */
    description?: string;
    /**
     * Environment
     */
    environment: string;
    /**
     * Id
     */
    id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Owner
     */
    owner: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Description
     */
    description?: string;
    /**
     * Name
     */
    name: string;
};

/**
 * Run
 */
export type Run = {
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Input Tokens
     */
    input_tokens?: number;
    /**
     * Output Tokens
     */
    output_tokens?: number;
    /**
     * Prompt Key
     */
    prompt_key: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Updated At
     */
    updated_at?: string;
    /**
     * Workflow Name
     */
    workflow_name?: string | null;
};

/**
 * Task
 */
export type Task = {
    /**
     * Agent
     */
    agent: string;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * History Key
     */
    history_key?: string | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Agent
     */
    agent?: string;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Title
     */
    title: string;
};

/**
 * TaskDetail
 */
export type TaskDetail = {
    /**
     * Artifacts
     */
    artifacts: Array<Artifact>;
    /**
     * Events
     */
    events: Array<Event>;
    /**
     * Live Progress
     */
    live_progress?: {
        [key: string]: string;
    };
    /**
     * Messages
     */
    messages: Array<MessageRead>;
    /**
     * Runs
     */
    runs: Array<Run>;
    task: Task;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VerificationCreate
 */
export type VerificationCreate = {
    /**
     * Environment
     */
    environment?: string;
};

/**
 * VerificationRead
 */
export type VerificationRead = {
    /**
     * Component
     */
    component: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Environment
     */
    environment: string;
    /**
     * Evidence
     */
    evidence: string;
    /**
     * Id
     */
    id: string;
    /**
     * Subject
     */
    subject: string;
};

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type ListAgentsResponses = {
    /**
     * Response List Agents
     *
     * Successful Response
     */
    200: Array<AgentRead>;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type ReadAuthConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/config';
};

export type ReadAuthConfigResponses = {
    /**
     * Successful Response
     */
    200: AuthConfig;
};

export type ReadAuthConfigResponse = ReadAuthConfigResponses[keyof ReadAuthConfigResponses];

export type ReadIdentityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type ReadIdentityResponses = {
    /**
     * Successful Response
     */
    200: Principal;
};

export type ReadIdentityResponse = ReadIdentityResponses[keyof ReadIdentityResponses];

export type ListComponentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Environment
         */
        environment?: string;
    };
    url: '/api/components';
};

export type ListComponentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListComponentsError = ListComponentsErrors[keyof ListComponentsErrors];

export type ListComponentsResponses = {
    /**
     * Response List Components
     *
     * Successful Response
     */
    200: Array<ComponentRead>;
};

export type ListComponentsResponse = ListComponentsResponses[keyof ListComponentsResponses];

export type ReadMigrationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Environment
         */
        environment?: string;
    };
    url: '/api/migrations';
};

export type ReadMigrationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadMigrationsError = ReadMigrationsErrors[keyof ReadMigrationsErrors];

export type ReadMigrationsResponses = {
    /**
     * Successful Response
     */
    200: MigrationRead;
};

export type ReadMigrationsResponse = ReadMigrationsResponses[keyof ReadMigrationsResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type ListProjectsResponses = {
    /**
     * Response List Projects
     *
     * Successful Response
     */
    200: Array<Project>;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/projects';
};

export type CreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Successful Response
     */
    201: Project;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}';
};

export type DeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type ListTasksData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tasks';
};

export type ListTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTasksError = ListTasksErrors[keyof ListTasksErrors];

export type ListTasksResponses = {
    /**
     * Response List Tasks
     *
     * Successful Response
     */
    200: Array<Task>;
};

export type ListTasksResponse = ListTasksResponses[keyof ListTasksResponses];

export type CreateTaskData = {
    body: TaskCreate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/projects/{project_id}/tasks';
};

export type CreateTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTaskError = CreateTaskErrors[keyof CreateTaskErrors];

export type CreateTaskResponses = {
    /**
     * Successful Response
     */
    201: Task;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type DeleteTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type DeleteTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTaskError = DeleteTaskErrors[keyof DeleteTaskErrors];

export type DeleteTaskResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTaskResponse = DeleteTaskResponses[keyof DeleteTaskResponses];

export type ReadTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}';
};

export type ReadTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTaskError = ReadTaskErrors[keyof ReadTaskErrors];

export type ReadTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskDetail;
};

export type ReadTaskResponse = ReadTaskResponses[keyof ReadTaskResponses];

export type ReadArtifactData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
        /**
         * Artifact Id
         */
        artifact_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}/artifacts/{artifact_id}';
};

export type ReadArtifactErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadArtifactError = ReadArtifactErrors[keyof ReadArtifactErrors];

export type ReadArtifactResponses = {
    /**
     * Response Read Artifact
     *
     * Successful Response
     */
    200: string;
};

export type ReadArtifactResponse = ReadArtifactResponses[keyof ReadArtifactResponses];

export type CancelTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}/cancel';
};

export type CancelTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelTaskError = CancelTaskErrors[keyof CancelTaskErrors];

export type CancelTaskResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CancelTaskResponse = CancelTaskResponses[keyof CancelTaskResponses];

export type SendMessageData = {
    body: MessageCreate;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/tasks/{task_id}/messages';
};

export type SendMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageError = SendMessageErrors[keyof SendMessageErrors];

export type SendMessageResponses = {
    /**
     * Successful Response
     */
    201: Run;
};

export type SendMessageResponse = SendMessageResponses[keyof SendMessageResponses];

export type ListVerificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Environment
         */
        environment?: string;
    };
    url: '/api/verifications';
};

export type ListVerificationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListVerificationsError = ListVerificationsErrors[keyof ListVerificationsErrors];

export type ListVerificationsResponses = {
    /**
     * Response List Verifications
     *
     * Successful Response
     */
    200: Array<VerificationRead>;
};

export type ListVerificationsResponse = ListVerificationsResponses[keyof ListVerificationsResponses];

export type RunVerificationData = {
    body: VerificationCreate;
    path?: never;
    query?: never;
    url: '/api/verifications';
};

export type RunVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunVerificationError = RunVerificationErrors[keyof RunVerificationErrors];

export type RunVerificationResponses = {
    /**
     * Successful Response
     */
    201: VerificationRead;
};

export type RunVerificationResponse = RunVerificationResponses[keyof RunVerificationResponses];

export type ReadLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/livez';
};

export type ReadLivenessResponses = {
    /**
     * Response Read Liveness
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadLivenessResponse = ReadLivenessResponses[keyof ReadLivenessResponses];

export type ReadReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadReadinessResponses = {
    /**
     * Response Read Readiness
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadReadinessResponse = ReadReadinessResponses[keyof ReadReadinessResponses];
