---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-server
  namespace: ai-models
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-server
  template:
    metadata:
      labels:
        app: inference-server
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4 # Schedule on L4 nodes
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-pvc
      containers:
        - name: inference
          image: anthonycorletti/krm-examples-fastapi-gpu # Placeholder
          command: ["python", "main.py"]
          env:
            - name: APP_MODE
              value: "infer"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1 # Request 1 GPU from the node
          volumeMounts:
            - name: model-storage
              mountPath: /models
