---
apiVersion: v1
kind: Service
metadata:
  name: inference-server
  namespace: trainer-server
spec:
  selector:
    app: inference-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP # Use LoadBalancer if you want external access from the internet or another external network
