# k8s/base/inference-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-server
  namespace: trainer-server
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: inference-server
  template:
    metadata:
      labels:
        app: inference-server
    spec:
      nodeSelector:
        node-type: inference
      containers:
        - name: inference
          imagePullPolicy: Always
          image: anthonycorletti/krm-examples-python-trainer-server:latest
          env:
            - name: APP_MODE
              value: "infer"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
              memory: "2Gi"
              cpu: "1"
