apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-models

resources:
  - namespace.yaml
  - pvc.yaml
  - rbac.yaml
  - api-deployment.yaml
  - api-service.yaml
  - inference-deployment.yaml
  - inference-service.yaml
