apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: python-trainer-server
build:
  artifacts:
    - image: anthonycorletti/krm-examples-python-trainer-server
      context: . # context is the root of this example
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s/base
profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          - k8s/profiles/dev
