apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: platform-nightly-export
spec:
  suspend: false
  schedules: ['0 2 * * *']
  timezone: UTC
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  workflowSpec:
    workflowTemplateRef:
      name: platform-export-schedule
