apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-cluster
resources:
- workload.yaml
- service.yaml
configMapGenerator:
- name: prometheus
  files:
  - prometheus.yaml
  - alerts.yaml
