apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../vendor/envoy-gateway
namespace: platform-cluster
patches:
- target:
    kind: Namespace
    name: envoy-gateway-system
  patch: "$patch: delete\napiVersion: v1\nkind: Namespace\nmetadata:\n  name: envoy-gateway-system\n"
- target:
    kind: MutatingWebhookConfiguration
    name: envoy-gateway-topology-injector.envoy-gateway-system
  patch: "- op: replace\n  path: /webhooks/0/namespaceSelector/matchExpressions/0/values\n\
    \  value:\n  - platform-cluster\n"
- target:
    kind: MutatingWebhookConfiguration
    name: envoy-gateway-topology-injector.envoy-gateway-system
  patch: "- op: replace\n  path: /metadata/name\n  value: envoy-gateway-topology-injector.platform-cluster\n"
- target:
    kind: ClusterRole
    name: eg-gateway-helm-certgen:envoy-gateway-system
  patch: "- op: replace\n  path: /rules/1/resourceNames\n  value: [envoy-gateway-topology-injector.platform-cluster]\n"
