apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-cluster
resources:
  - ../../vendor/cloudnative-pg
images:
  - name: ghcr.io/cloudnative-pg/cloudnative-pg
    newTag: 1.30.0
    digest: sha256:a2701eb97cdd2a34b1fdb2cb51987f544b706e40bec72ae7146cd8580efefebb
patches:
  - target:
      kind: Namespace
      name: cnpg-system
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cnpg-system
  - target:
      kind: Deployment
      name: cnpg-controller-manager
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cnpg-controller-manager
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: OPERATOR_IMAGE_NAME
                    value: ghcr.io/cloudnative-pg/cloudnative-pg:1.30.0@sha256:a2701eb97cdd2a34b1fdb2cb51987f544b706e40bec72ae7146cd8580efefebb
