---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-workers
spec:
  selector:
    matchLabels:
      app: go-workers
  template:
    spec:
      containers:
        - name: go-workers
          image: anthonycorletti/krm-examples-go-workers:latest
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
