apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/apps/migrations
images:
- name: platform-server
  newName: platform-starter-server
  newTag: local
- name: platform-web
  newName: platform-starter-web
  newTag: local
